/**
 * This file was auto-generated by scripts/generate-operations.ts.
 * DO NOT EDIT BY HAND.
 *
 * Switch-based dispatch for the builder proxy (no route object / SPEC).
 */

import type { ac } from './client';
import { invokeEndpoint } from './invoke-endpoint';

type Client = ReturnType<typeof ac>;

export type TagAccess =
  | { kind: 'root-op' }
  | { kind: 'group'; params: string[] };

export function resolveTagAccess(tag: string, key: string): TagAccess | undefined {
  switch (tag) {
    case "authentication":
      switch (key) {
        case "createOAuthToken":
          return { kind: 'root-op' };
        default:
          return undefined;
      }
    case "blocks":
      switch (key) {
        case "batchCreateBlocks":
          return { kind: 'root-op' };
        case "createBlock":
          return { kind: 'root-op' };
        case "byBatchId":
          return { kind: 'group', params: ["batch_id"] };
        case "byId":
          return { kind: 'group', params: ["id"] };
        default:
          return undefined;
      }
    case "channels":
      switch (key) {
        case "createChannel":
          return { kind: 'root-op' };
        case "byId":
          return { kind: 'group', params: ["id"] };
        default:
          return undefined;
      }
    case "comments":
      switch (key) {
        case "byId":
          return { kind: 'group', params: ["id"] };
        default:
          return undefined;
      }
    case "connections":
      switch (key) {
        case "createConnection":
          return { kind: 'root-op' };
        case "byId":
          return { kind: 'group', params: ["id"] };
        default:
          return undefined;
      }
    case "groups":
      switch (key) {
        case "byId":
          return { kind: 'group', params: ["id"] };
        default:
          return undefined;
      }
    case "search":
      switch (key) {
        case "search":
          return { kind: 'root-op' };
        default:
          return undefined;
      }
    case "system":
      switch (key) {
        case "getOpenapiSpec":
          return { kind: 'root-op' };
        case "getOpenapiSpecJson":
          return { kind: 'root-op' };
        case "getPing":
          return { kind: 'root-op' };
        default:
          return undefined;
      }
    case "uploads":
      switch (key) {
        case "presignUpload":
          return { kind: 'root-op' };
        default:
          return undefined;
      }
    case "users":
      switch (key) {
        case "getCurrentUser":
          return { kind: 'root-op' };
        case "byId":
          return { kind: 'group', params: ["id"] };
        default:
          return undefined;
      }
    default:
      return undefined;
  }
}

export function dispatchRootOp(client: Client, tag: string, opId: string, args: unknown[]): unknown {
  switch (tag) {
    case "authentication":
      switch (opId) {
        case "createOAuthToken":
          return invokeEndpoint(client.v3.oauth.token['$post'], {}, args);
        default:
          throw new Error(`Unknown operation ${opId} on tag authentication`);
      }
    case "blocks":
      switch (opId) {
        case "batchCreateBlocks":
          return invokeEndpoint(client.v3.blocks.batch['$post'], {}, args);
        case "createBlock":
          return invokeEndpoint(client.v3.blocks['$post'], {}, args);
        default:
          throw new Error(`Unknown operation ${opId} on tag blocks`);
      }
    case "channels":
      switch (opId) {
        case "createChannel":
          return invokeEndpoint(client.v3.channels['$post'], {}, args);
        default:
          throw new Error(`Unknown operation ${opId} on tag channels`);
      }
    case "comments":
      throw new Error(`Tag comments has no root-level operations (got ${opId})`);
    case "connections":
      switch (opId) {
        case "createConnection":
          return invokeEndpoint(client.v3.connections['$post'], {}, args);
        default:
          throw new Error(`Unknown operation ${opId} on tag connections`);
      }
    case "groups":
      throw new Error(`Tag groups has no root-level operations (got ${opId})`);
    case "search":
      switch (opId) {
        case "search":
          return invokeEndpoint(client.v3.search['$get'], {}, args);
        default:
          throw new Error(`Unknown operation ${opId} on tag search`);
      }
    case "system":
      switch (opId) {
        case "getOpenapiSpec":
          return invokeEndpoint(client.v3.openapi['$get'], {}, args);
        case "getOpenapiSpecJson":
          return invokeEndpoint(client.v3["openapi.json"]['$get'], {}, args);
        case "getPing":
          return invokeEndpoint(client.v3.ping['$get'], {}, args);
        default:
          throw new Error(`Unknown operation ${opId} on tag system`);
      }
    case "uploads":
      switch (opId) {
        case "presignUpload":
          return invokeEndpoint(client.v3.uploads.presign['$post'], {}, args);
        default:
          throw new Error(`Unknown operation ${opId} on tag uploads`);
      }
    case "users":
      switch (opId) {
        case "getCurrentUser":
          return invokeEndpoint(client.v3.me['$get'], {}, args);
        default:
          throw new Error(`Unknown operation ${opId} on tag users`);
      }
    default:
      throw new Error(`Unknown tag ${tag}`);
  }
}

export function dispatchGroupedOp(
  client: Client,
  tag: string,
  group: string,
  opId: string,
  bound: Record<string, unknown>,
  args: unknown[],
): unknown {
  switch (tag) {
    case "authentication":
      throw new Error(`Tag authentication has no grouped operations (got group ${group})`);
    case "blocks":
      switch (group) {
        case "byBatchId":
          switch (opId) {
            case "getBatchStatus":
              return invokeEndpoint(client.v3.blocks.batch[':batch_id']['$get'], bound, args);
            default:
              throw new Error(`Unknown operation ${opId} in group byBatchId (tag blocks)`);
          }
        case "byId":
          switch (opId) {
            case "createBlockComment":
              return invokeEndpoint(client.v3.blocks[':id'].comments['$post'], bound, args);
            case "getBlock":
              return invokeEndpoint(client.v3.blocks[':id']['$get'], bound, args);
            case "getBlockComments":
              return invokeEndpoint(client.v3.blocks[':id'].comments['$get'], bound, args);
            case "getBlockConnections":
              return invokeEndpoint(client.v3.blocks[':id'].connections['$get'], bound, args);
            case "updateBlock":
              return invokeEndpoint(client.v3.blocks[':id']['$put'], bound, args);
            default:
              throw new Error(`Unknown operation ${opId} in group byId (tag blocks)`);
          }
        default:
          throw new Error(`Unknown group for tag blocks: ${group}`);
      }
    case "channels":
      switch (group) {
        case "byId":
          switch (opId) {
            case "deleteChannel":
              return invokeEndpoint(client.v3.channels[':id']['$delete'], bound, args);
            case "getChannel":
              return invokeEndpoint(client.v3.channels[':id']['$get'], bound, args);
            case "getChannelConnections":
              return invokeEndpoint(client.v3.channels[':id'].connections['$get'], bound, args);
            case "getChannelContents":
              return invokeEndpoint(client.v3.channels[':id'].contents['$get'], bound, args);
            case "getChannelFollowers":
              return invokeEndpoint(client.v3.channels[':id'].followers['$get'], bound, args);
            case "updateChannel":
              return invokeEndpoint(client.v3.channels[':id']['$put'], bound, args);
            default:
              throw new Error(`Unknown operation ${opId} in group byId (tag channels)`);
          }
        default:
          throw new Error(`Unknown group for tag channels: ${group}`);
      }
    case "comments":
      switch (group) {
        case "byId":
          switch (opId) {
            case "deleteComment":
              return invokeEndpoint(client.v3.comments[':id']['$delete'], bound, args);
            default:
              throw new Error(`Unknown operation ${opId} in group byId (tag comments)`);
          }
        default:
          throw new Error(`Unknown group for tag comments: ${group}`);
      }
    case "connections":
      switch (group) {
        case "byId":
          switch (opId) {
            case "deleteConnection":
              return invokeEndpoint(client.v3.connections[':id']['$delete'], bound, args);
            case "getConnection":
              return invokeEndpoint(client.v3.connections[':id']['$get'], bound, args);
            case "moveConnection":
              return invokeEndpoint(client.v3.connections[':id'].move['$post'], bound, args);
            default:
              throw new Error(`Unknown operation ${opId} in group byId (tag connections)`);
          }
        default:
          throw new Error(`Unknown group for tag connections: ${group}`);
      }
    case "groups":
      switch (group) {
        case "byId":
          switch (opId) {
            case "getGroup":
              return invokeEndpoint(client.v3.groups[':id']['$get'], bound, args);
            case "getGroupContents":
              return invokeEndpoint(client.v3.groups[':id'].contents['$get'], bound, args);
            case "getGroupFollowers":
              return invokeEndpoint(client.v3.groups[':id'].followers['$get'], bound, args);
            default:
              throw new Error(`Unknown operation ${opId} in group byId (tag groups)`);
          }
        default:
          throw new Error(`Unknown group for tag groups: ${group}`);
      }
    case "search":
      throw new Error(`Tag search has no grouped operations (got group ${group})`);
    case "system":
      throw new Error(`Tag system has no grouped operations (got group ${group})`);
    case "uploads":
      throw new Error(`Tag uploads has no grouped operations (got group ${group})`);
    case "users":
      switch (group) {
        case "byId":
          switch (opId) {
            case "getUser":
              return invokeEndpoint(client.v3.users[':id']['$get'], bound, args);
            case "getUserContents":
              return invokeEndpoint(client.v3.users[':id'].contents['$get'], bound, args);
            case "getUserFollowers":
              return invokeEndpoint(client.v3.users[':id'].followers['$get'], bound, args);
            case "getUserFollowing":
              return invokeEndpoint(client.v3.users[':id'].following['$get'], bound, args);
            default:
              throw new Error(`Unknown operation ${opId} in group byId (tag users)`);
          }
        default:
          throw new Error(`Unknown group for tag users: ${group}`);
      }
    default:
      throw new Error(`Unknown tag ${tag}`);
  }
}
