/** Auto-generated by scripts/generate-operations.ts. Do not edit by hand. */

import type { ac } from './client';

type Client = ReturnType<typeof ac>;
type Fn = (...args: any[]) => any;

type ParamValue<F extends Fn, K extends string> = Parameters<F> extends [infer First, ...any]
  ? First extends { param: infer P }
    ? K extends keyof P ? P[K] : string | number
    : string | number
  : string | number;

export type BuilderShape = {
  authentication: {
    createOAuthToken: Client["v3"]["oauth"]["token"]['$post'];
  };
  blocks: {
    batchCreateBlocks: Client["v3"]["blocks"]["batch"]['$post'];
    createBlock: Client["v3"]["blocks"]['$post'];
    batch_id(value: ParamValue<Client["v3"]["blocks"]["batch"][':batch_id']['$get'], "batch_id">): {
      getBatchStatus: Client["v3"]["blocks"]["batch"][':batch_id']['$get'];
    };
    id(value: ParamValue<Client["v3"]["blocks"][':id']["comments"]['$post'], "id">): {
      createBlockComment: Client["v3"]["blocks"][':id']["comments"]['$post'];
      getBlock: Client["v3"]["blocks"][':id']['$get'];
      getBlockComments: Client["v3"]["blocks"][':id']["comments"]['$get'];
      getBlockConnections: Client["v3"]["blocks"][':id']["connections"]['$get'];
      updateBlock: Client["v3"]["blocks"][':id']['$put'];
    };
  };
  channels: {
    createChannel: Client["v3"]["channels"]['$post'];
    id(value: ParamValue<Client["v3"]["channels"][':id']['$delete'], "id">): {
      deleteChannel: Client["v3"]["channels"][':id']['$delete'];
      getChannel: Client["v3"]["channels"][':id']['$get'];
      getChannelConnections: Client["v3"]["channels"][':id']["connections"]['$get'];
      getChannelContents: Client["v3"]["channels"][':id']["contents"]['$get'];
      getChannelFollowers: Client["v3"]["channels"][':id']["followers"]['$get'];
      updateChannel: Client["v3"]["channels"][':id']['$put'];
    };
  };
  comments: {
    id(value: ParamValue<Client["v3"]["comments"][':id']['$delete'], "id">): {
      deleteComment: Client["v3"]["comments"][':id']['$delete'];
    };
  };
  connections: {
    createConnection: Client["v3"]["connections"]['$post'];
    id(value: ParamValue<Client["v3"]["connections"][':id']['$delete'], "id">): {
      deleteConnection: Client["v3"]["connections"][':id']['$delete'];
      getConnection: Client["v3"]["connections"][':id']['$get'];
      moveConnection: Client["v3"]["connections"][':id']["move"]['$post'];
    };
  };
  groups: {
    id(value: ParamValue<Client["v3"]["groups"][':id']['$get'], "id">): {
      getGroup: Client["v3"]["groups"][':id']['$get'];
      getGroupContents: Client["v3"]["groups"][':id']["contents"]['$get'];
      getGroupFollowers: Client["v3"]["groups"][':id']["followers"]['$get'];
    };
  };
  search: {
    search: Client["v3"]["search"]['$get'];
  };
  system: {
    getOpenapiSpec: Client["v3"]["openapi"]['$get'];
    getOpenapiSpecJson: Client["v3"]["openapi.json"]['$get'];
    getPing: Client["v3"]["ping"]['$get'];
  };
  uploads: {
    presignUpload: Client["v3"]["uploads"]["presign"]['$post'];
  };
  users: {
    getCurrentUser: Client["v3"]["me"]['$get'];
    id(value: ParamValue<Client["v3"]["users"][':id']['$get'], "id">): {
      getUser: Client["v3"]["users"][':id']['$get'];
      getUserContents: Client["v3"]["users"][':id']["contents"]['$get'];
      getUserFollowers: Client["v3"]["users"][':id']["followers"]['$get'];
      getUserFollowing: Client["v3"]["users"][':id']["following"]['$get'];
    };
  };
};

function invokeEndpoint(endpoint: Fn, boundParam: Record<string, unknown>, args: unknown[]) {
  if (!boundParam || Object.keys(boundParam).length === 0) return endpoint(...(args as any[]));
  if (args.length > 0 && typeof args[0] === "object" && args[0] !== null) {
    const first = args[0] as Record<string, unknown>;
    const merged = { ...first, param: { ...(first.param as object | undefined), ...boundParam } };
    return endpoint(merged, ...(args.slice(1) as any[]));
  }
  return endpoint({ param: boundParam }, ...(args as any[]));
}

const GROUP_PARAM_KEYS: Record<string, string[]> = {
  "blocks|batch_id": ["batch_id"],
  "blocks|id": ["id"],
  "channels|id": ["id"],
  "comments|id": ["id"],
  "connections|id": ["id"],
  "groups|id": ["id"],
  "users|id": ["id"],
};

const ROOT_ENDPOINTS: Record<string, (client: Client, args: unknown[]) => unknown> = {
  "authentication|createOAuthToken": (client, args) => invokeEndpoint(client.v3.oauth.token['$post'], {}, args),
  "blocks|batchCreateBlocks": (client, args) => invokeEndpoint(client.v3.blocks.batch['$post'], {}, args),
  "blocks|createBlock": (client, args) => invokeEndpoint(client.v3.blocks['$post'], {}, args),
  "channels|createChannel": (client, args) => invokeEndpoint(client.v3.channels['$post'], {}, args),
  "connections|createConnection": (client, args) => invokeEndpoint(client.v3.connections['$post'], {}, args),
  "search|search": (client, args) => invokeEndpoint(client.v3.search['$get'], {}, args),
  "system|getOpenapiSpec": (client, args) => invokeEndpoint(client.v3.openapi['$get'], {}, args),
  "system|getOpenapiSpecJson": (client, args) => invokeEndpoint(client.v3["openapi.json"]['$get'], {}, args),
  "system|getPing": (client, args) => invokeEndpoint(client.v3.ping['$get'], {}, args),
  "uploads|presignUpload": (client, args) => invokeEndpoint(client.v3.uploads.presign['$post'], {}, args),
  "users|getCurrentUser": (client, args) => invokeEndpoint(client.v3.me['$get'], {}, args),
};

const GROUP_ENDPOINTS: Record<string, (client: Client, bound: Record<string, unknown>, args: unknown[]) => unknown> = {
  "blocks|batch_id|getBatchStatus": (client, bound, args) => invokeEndpoint(client.v3.blocks.batch[':batch_id']['$get'], bound, args),
  "blocks|id|createBlockComment": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id'].comments['$post'], bound, args),
  "blocks|id|getBlock": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id']['$get'], bound, args),
  "blocks|id|getBlockComments": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id'].comments['$get'], bound, args),
  "blocks|id|getBlockConnections": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id'].connections['$get'], bound, args),
  "blocks|id|updateBlock": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id']['$put'], bound, args),
  "channels|id|deleteChannel": (client, bound, args) => invokeEndpoint(client.v3.channels[':id']['$delete'], bound, args),
  "channels|id|getChannel": (client, bound, args) => invokeEndpoint(client.v3.channels[':id']['$get'], bound, args),
  "channels|id|getChannelConnections": (client, bound, args) => invokeEndpoint(client.v3.channels[':id'].connections['$get'], bound, args),
  "channels|id|getChannelContents": (client, bound, args) => invokeEndpoint(client.v3.channels[':id'].contents['$get'], bound, args),
  "channels|id|getChannelFollowers": (client, bound, args) => invokeEndpoint(client.v3.channels[':id'].followers['$get'], bound, args),
  "channels|id|updateChannel": (client, bound, args) => invokeEndpoint(client.v3.channels[':id']['$put'], bound, args),
  "comments|id|deleteComment": (client, bound, args) => invokeEndpoint(client.v3.comments[':id']['$delete'], bound, args),
  "connections|id|deleteConnection": (client, bound, args) => invokeEndpoint(client.v3.connections[':id']['$delete'], bound, args),
  "connections|id|getConnection": (client, bound, args) => invokeEndpoint(client.v3.connections[':id']['$get'], bound, args),
  "connections|id|moveConnection": (client, bound, args) => invokeEndpoint(client.v3.connections[':id'].move['$post'], bound, args),
  "groups|id|getGroup": (client, bound, args) => invokeEndpoint(client.v3.groups[':id']['$get'], bound, args),
  "groups|id|getGroupContents": (client, bound, args) => invokeEndpoint(client.v3.groups[':id'].contents['$get'], bound, args),
  "groups|id|getGroupFollowers": (client, bound, args) => invokeEndpoint(client.v3.groups[':id'].followers['$get'], bound, args),
  "users|id|getUser": (client, bound, args) => invokeEndpoint(client.v3.users[':id']['$get'], bound, args),
  "users|id|getUserContents": (client, bound, args) => invokeEndpoint(client.v3.users[':id'].contents['$get'], bound, args),
  "users|id|getUserFollowers": (client, bound, args) => invokeEndpoint(client.v3.users[':id'].followers['$get'], bound, args),
  "users|id|getUserFollowing": (client, bound, args) => invokeEndpoint(client.v3.users[':id'].following['$get'], bound, args),
};

function normalizeGroupParams(params: string[], value: unknown): Record<string, unknown> {
  if (params.length === 1) return { [params[0]!]: value };
  return value as Record<string, unknown>;
}

type BuilderApplyOpts = { client: Client; path: string[]; args: unknown[]; bound?: Record<string, unknown> };

function builderApply(opts: BuilderApplyOpts): unknown {
  const { client, path, args, bound } = opts;
  const key = path.join("|");
  if (path.length === 2 && !bound) {
    const paramKeys = GROUP_PARAM_KEYS[key];
    if (paramKeys) {
      return createBuilderProxy(client, path, normalizeGroupParams(paramKeys, args[0]));
    }
    const run = ROOT_ENDPOINTS[key];
    if (run) return run(client, args);
    return undefined;
  }
  if (path.length === 3 && bound) {
    const run = GROUP_ENDPOINTS[key];
    if (run) return run(client, bound, args);
  }
  return undefined;
}

function createBuilderProxy(client: Client, path: string[] = [], bound?: Record<string, unknown>) {
  const proxy: unknown = new Proxy(() => {}, {
    get(_obj, prop) {
      if (typeof prop !== "string" || prop === "then") return undefined;
      return createBuilderProxy(client, [...path, prop], bound);
    },
    apply(_1, _2, args: unknown[]) {
      return builderApply({ client, path, args, bound });
    },
  });
  return proxy;
}

export interface Builder extends BuilderShape {}

export class Builder {
  constructor(client: Client) {
    return createBuilderProxy(client) as unknown as Builder;
  }
}
