/**
 * This file was auto-generated by scripts/generate-operations.ts.
 * DO NOT EDIT BY HAND.
 *
 * Types describe the surface; runtime is one Proxy whose handler uses depth `d` (0→tag,
 * 1→endpoint or param-group, 2→endpoint in group) plus generated lookup tables — no switch on tag.
 */

import type { ac } from './client';

type Client = ReturnType<typeof ac>;
type Fn = (...args: any[]) => any;

type StripBoundParam<Input, Keys extends string> = Input extends { param: infer P }
  ? Omit<Input, 'param'> & (Omit<P, Keys> extends Record<string, never> ? {} : { param: Omit<P, Keys> })
  : Input;

type BoundArgs<Args extends unknown[], Keys extends string> =
  Args extends [infer First, ...infer Rest]
    ? First extends { param: infer P }
      ? | Args
        | (Omit<P, Keys> extends Record<string, never>
            ? Rest | [StripBoundParam<First, Keys>, ...Rest]
            : [StripBoundParam<First, Keys>, ...Rest])
      : Args
    : Args;

type BoundCall<F extends Fn, Keys extends string> = F extends (...args: infer A) => infer R
  ? (...args: BoundArgs<A, Keys>) => R
  : never;

type ParamValue<F extends Fn, K extends string> = Parameters<F> extends [infer First, ...any]
  ? First extends { param: infer P }
    ? K extends keyof P ? P[K] : string | number
    : string | number
  : string | number;

export type BuilderShape = {
  authentication: {
    createOAuthToken: BoundCall<Client["v3"]["oauth"]["token"]['$post'], never>;
  };
  blocks: {
    batchCreateBlocks: BoundCall<Client["v3"]["blocks"]["batch"]['$post'], never>;
    createBlock: BoundCall<Client["v3"]["blocks"]['$post'], never>;
    batchId(value: ParamValue<Client["v3"]["blocks"]["batch"][':batch_id']['$get'], "batch_id">): {
      getBatchStatus: BoundCall<Client["v3"]["blocks"]["batch"][':batch_id']['$get'], "batch_id">;
    };
    id(value: ParamValue<Client["v3"]["blocks"][':id']["comments"]['$post'], "id">): {
      createBlockComment: BoundCall<Client["v3"]["blocks"][':id']["comments"]['$post'], "id">;
      getBlock: BoundCall<Client["v3"]["blocks"][':id']['$get'], "id">;
      getBlockComments: BoundCall<Client["v3"]["blocks"][':id']["comments"]['$get'], "id">;
      getBlockConnections: BoundCall<Client["v3"]["blocks"][':id']["connections"]['$get'], "id">;
      updateBlock: BoundCall<Client["v3"]["blocks"][':id']['$put'], "id">;
    };
  };
  channels: {
    createChannel: BoundCall<Client["v3"]["channels"]['$post'], never>;
    id(value: ParamValue<Client["v3"]["channels"][':id']['$delete'], "id">): {
      deleteChannel: BoundCall<Client["v3"]["channels"][':id']['$delete'], "id">;
      getChannel: BoundCall<Client["v3"]["channels"][':id']['$get'], "id">;
      getChannelConnections: BoundCall<Client["v3"]["channels"][':id']["connections"]['$get'], "id">;
      getChannelContents: BoundCall<Client["v3"]["channels"][':id']["contents"]['$get'], "id">;
      getChannelFollowers: BoundCall<Client["v3"]["channels"][':id']["followers"]['$get'], "id">;
      updateChannel: BoundCall<Client["v3"]["channels"][':id']['$put'], "id">;
    };
  };
  comments: {
    id(value: ParamValue<Client["v3"]["comments"][':id']['$delete'], "id">): {
      deleteComment: BoundCall<Client["v3"]["comments"][':id']['$delete'], "id">;
    };
  };
  connections: {
    createConnection: BoundCall<Client["v3"]["connections"]['$post'], never>;
    id(value: ParamValue<Client["v3"]["connections"][':id']['$delete'], "id">): {
      deleteConnection: BoundCall<Client["v3"]["connections"][':id']['$delete'], "id">;
      getConnection: BoundCall<Client["v3"]["connections"][':id']['$get'], "id">;
      moveConnection: BoundCall<Client["v3"]["connections"][':id']["move"]['$post'], "id">;
    };
  };
  groups: {
    id(value: ParamValue<Client["v3"]["groups"][':id']['$get'], "id">): {
      getGroup: BoundCall<Client["v3"]["groups"][':id']['$get'], "id">;
      getGroupContents: BoundCall<Client["v3"]["groups"][':id']["contents"]['$get'], "id">;
      getGroupFollowers: BoundCall<Client["v3"]["groups"][':id']["followers"]['$get'], "id">;
    };
  };
  search: {
    search: BoundCall<Client["v3"]["search"]['$get'], never>;
  };
  system: {
    getOpenapiSpec: BoundCall<Client["v3"]["openapi"]['$get'], never>;
    getOpenapiSpecJson: BoundCall<Client["v3"]["openapi.json"]['$get'], never>;
    getPing: BoundCall<Client["v3"]["ping"]['$get'], never>;
  };
  uploads: {
    presignUpload: BoundCall<Client["v3"]["uploads"]["presign"]['$post'], never>;
  };
  users: {
    getCurrentUser: BoundCall<Client["v3"]["me"]['$get'], never>;
    id(value: ParamValue<Client["v3"]["users"][':id']['$get'], "id">): {
      getUser: BoundCall<Client["v3"]["users"][':id']['$get'], "id">;
      getUserContents: BoundCall<Client["v3"]["users"][':id']["contents"]['$get'], "id">;
      getUserFollowers: BoundCall<Client["v3"]["users"][':id']["followers"]['$get'], "id">;
      getUserFollowing: BoundCall<Client["v3"]["users"][':id']["following"]['$get'], "id">;
    };
  };
};

function invokeEndpoint(endpoint: Fn, boundParam: Record<string, unknown>, args: unknown[]) {
  if (!boundParam || Object.keys(boundParam).length === 0) return endpoint(...(args as any[]));
  if (args.length > 0 && typeof args[0] === "object" && args[0] !== null) {
    const first = args[0] as Record<string, unknown>;
    const merged = { ...first, param: { ...(first.param as object | undefined), ...boundParam } };
    return endpoint(merged, ...(args.slice(1) as any[]));
  }
  return endpoint({ param: boundParam }, ...(args as any[]));
}

type TagAccess =
  | { kind: 'root-endpoint' }
  | { kind: 'param-group'; params: string[] };

const TAG_ACCESS: Record<string, Record<string, TagAccess>> = {
  authentication: {
    createOAuthToken: { kind: 'root-endpoint' },
  },
  blocks: {
    batchCreateBlocks: { kind: 'root-endpoint' },
    createBlock: { kind: 'root-endpoint' },
    batchId: { kind: 'param-group', params: ["batch_id"] },
    id: { kind: 'param-group', params: ["id"] },
  },
  channels: {
    createChannel: { kind: 'root-endpoint' },
    id: { kind: 'param-group', params: ["id"] },
  },
  comments: {
    id: { kind: 'param-group', params: ["id"] },
  },
  connections: {
    createConnection: { kind: 'root-endpoint' },
    id: { kind: 'param-group', params: ["id"] },
  },
  groups: {
    id: { kind: 'param-group', params: ["id"] },
  },
  search: {
    search: { kind: 'root-endpoint' },
  },
  system: {
    getOpenapiSpec: { kind: 'root-endpoint' },
    getOpenapiSpecJson: { kind: 'root-endpoint' },
    getPing: { kind: 'root-endpoint' },
  },
  uploads: {
    presignUpload: { kind: 'root-endpoint' },
  },
  users: {
    getCurrentUser: { kind: 'root-endpoint' },
    id: { kind: 'param-group', params: ["id"] },
  },
};

const DISPATCH_ROOT: Record<string, Record<string, (client: Client, args: unknown[]) => unknown>> = {
  authentication: {
    createOAuthToken: (client, args) => invokeEndpoint(client.v3.oauth.token['$post'], {}, args),
  },
  blocks: {
    batchCreateBlocks: (client, args) => invokeEndpoint(client.v3.blocks.batch['$post'], {}, args),
    createBlock: (client, args) => invokeEndpoint(client.v3.blocks['$post'], {}, args),
  },
  channels: {
    createChannel: (client, args) => invokeEndpoint(client.v3.channels['$post'], {}, args),
  },
  connections: {
    createConnection: (client, args) => invokeEndpoint(client.v3.connections['$post'], {}, args),
  },
  search: {
    search: (client, args) => invokeEndpoint(client.v3.search['$get'], {}, args),
  },
  system: {
    getOpenapiSpec: (client, args) => invokeEndpoint(client.v3.openapi['$get'], {}, args),
    getOpenapiSpecJson: (client, args) => invokeEndpoint(client.v3["openapi.json"]['$get'], {}, args),
    getPing: (client, args) => invokeEndpoint(client.v3.ping['$get'], {}, args),
  },
  uploads: {
    presignUpload: (client, args) => invokeEndpoint(client.v3.uploads.presign['$post'], {}, args),
  },
  users: {
    getCurrentUser: (client, args) => invokeEndpoint(client.v3.me['$get'], {}, args),
  },
};

const DISPATCH_GROUP: Record<string, Record<string, Record<string, (client: Client, bound: Record<string, unknown>, args: unknown[]) => unknown>>> = {
  blocks: {
    batchId: {
      getBatchStatus: (client, bound, args) => invokeEndpoint(client.v3.blocks.batch[':batch_id']['$get'], bound, args),
    },
    id: {
      createBlockComment: (client, bound, args) => invokeEndpoint(client.v3.blocks[':id'].comments['$post'], bound, args),
      getBlock: (client, bound, args) => invokeEndpoint(client.v3.blocks[':id']['$get'], bound, args),
      getBlockComments: (client, bound, args) => invokeEndpoint(client.v3.blocks[':id'].comments['$get'], bound, args),
      getBlockConnections: (client, bound, args) => invokeEndpoint(client.v3.blocks[':id'].connections['$get'], bound, args),
      updateBlock: (client, bound, args) => invokeEndpoint(client.v3.blocks[':id']['$put'], bound, args),
    },
  },
  channels: {
    id: {
      deleteChannel: (client, bound, args) => invokeEndpoint(client.v3.channels[':id']['$delete'], bound, args),
      getChannel: (client, bound, args) => invokeEndpoint(client.v3.channels[':id']['$get'], bound, args),
      getChannelConnections: (client, bound, args) => invokeEndpoint(client.v3.channels[':id'].connections['$get'], bound, args),
      getChannelContents: (client, bound, args) => invokeEndpoint(client.v3.channels[':id'].contents['$get'], bound, args),
      getChannelFollowers: (client, bound, args) => invokeEndpoint(client.v3.channels[':id'].followers['$get'], bound, args),
      updateChannel: (client, bound, args) => invokeEndpoint(client.v3.channels[':id']['$put'], bound, args),
    },
  },
  comments: {
    id: {
      deleteComment: (client, bound, args) => invokeEndpoint(client.v3.comments[':id']['$delete'], bound, args),
    },
  },
  connections: {
    id: {
      deleteConnection: (client, bound, args) => invokeEndpoint(client.v3.connections[':id']['$delete'], bound, args),
      getConnection: (client, bound, args) => invokeEndpoint(client.v3.connections[':id']['$get'], bound, args),
      moveConnection: (client, bound, args) => invokeEndpoint(client.v3.connections[':id'].move['$post'], bound, args),
    },
  },
  groups: {
    id: {
      getGroup: (client, bound, args) => invokeEndpoint(client.v3.groups[':id']['$get'], bound, args),
      getGroupContents: (client, bound, args) => invokeEndpoint(client.v3.groups[':id'].contents['$get'], bound, args),
      getGroupFollowers: (client, bound, args) => invokeEndpoint(client.v3.groups[':id'].followers['$get'], bound, args),
    },
  },
  users: {
    id: {
      getUser: (client, bound, args) => invokeEndpoint(client.v3.users[':id']['$get'], bound, args),
      getUserContents: (client, bound, args) => invokeEndpoint(client.v3.users[':id'].contents['$get'], bound, args),
      getUserFollowers: (client, bound, args) => invokeEndpoint(client.v3.users[':id'].followers['$get'], bound, args),
      getUserFollowing: (client, bound, args) => invokeEndpoint(client.v3.users[':id'].following['$get'], bound, args),
    },
  },
};

type BuilderNav =
  | { d: 0 }
  | { d: 1; tag: string }
  | { d: 2; tag: string; group: string; bound: Record<string, unknown> };

function normalizeGroupParams(params: string[], value: unknown): Record<string, unknown> {
  if (params.length === 1) return { [params[0]!]: value };
  return value as Record<string, unknown>;
}

const noop = (): unknown => undefined;

/**
 * One Proxy: `d` is depth (0 = choose tag, 1 = endpoint or param-group, 2 = endpoint under group).
 * No switch on tag at runtime — only table lookups + depth.
 */
function createBuilderNav(client: Client, nav: BuilderNav = { d: 0 }) {
  return new Proxy(noop, {
    get(_t, key: string) {
      if (typeof key !== "string" || key === "then") return undefined;
      if (nav.d === 0) {
        return createBuilderNav(client, { d: 1, tag: key });
      }
      if (nav.d === 1) {
        const acc = TAG_ACCESS[nav.tag]?.[key];
        if (!acc) return undefined;
        if (acc.kind === 'root-endpoint') {
          const run = DISPATCH_ROOT[nav.tag]?.[key];
          if (!run) return undefined;
          return (...args: unknown[]) => run(client, args);
        }
        return (value: unknown) => {
          const bound = normalizeGroupParams(acc.params, value);
          return createBuilderNav(client, { d: 2, tag: nav.tag, group: key, bound });
        };
      }
      if (nav.d === 2) {
        const run = DISPATCH_GROUP[nav.tag]?.[nav.group]?.[key];
        if (!run) return undefined;
        return (...args: unknown[]) => run(client, nav.bound, args);
      }
    },
  });
}

export interface Builder extends BuilderShape {}

export class Builder {
  constructor(client: Client) {
    return createBuilderNav(client) as unknown as Builder;
  }
}
