/** Auto-generated by scripts/generate-operations.ts. Do not edit by hand. */

import type { ac } from './client';

type Client = ReturnType<typeof ac>;
type Fn = (...args: any[]) => any;

type ParamValue<F extends Fn, K extends string> = Parameters<F> extends [infer First, ...any]
  ? First extends { param: infer P }
    ? K extends keyof P ? P[K] : string | number
    : string | number
  : string | number;

export type BuilderShape = {
  authentication: {
    createOAuthToken: Client["v3"]["oauth"]["token"]['$post'];
  };
  blocks: {
    batchCreateBlocks: Client["v3"]["blocks"]["batch"]['$post'];
    createBlock: Client["v3"]["blocks"]['$post'];
    batch_id(value: ParamValue<Client["v3"]["blocks"]["batch"][':batch_id']['$get'], "batch_id">): {
      getBatchStatus: Client["v3"]["blocks"]["batch"][':batch_id']['$get'];
    };
    id(value: ParamValue<Client["v3"]["blocks"][':id']["comments"]['$post'], "id">): {
      createBlockComment: Client["v3"]["blocks"][':id']["comments"]['$post'];
      getBlock: Client["v3"]["blocks"][':id']['$get'];
      getBlockComments: Client["v3"]["blocks"][':id']["comments"]['$get'];
      getBlockConnections: Client["v3"]["blocks"][':id']["connections"]['$get'];
      updateBlock: Client["v3"]["blocks"][':id']['$put'];
    };
  };
  channels: {
    createChannel: Client["v3"]["channels"]['$post'];
    id(value: ParamValue<Client["v3"]["channels"][':id']['$delete'], "id">): {
      deleteChannel: Client["v3"]["channels"][':id']['$delete'];
      getChannel: Client["v3"]["channels"][':id']['$get'];
      getChannelConnections: Client["v3"]["channels"][':id']["connections"]['$get'];
      getChannelContents: Client["v3"]["channels"][':id']["contents"]['$get'];
      getChannelFollowers: Client["v3"]["channels"][':id']["followers"]['$get'];
      updateChannel: Client["v3"]["channels"][':id']['$put'];
    };
  };
  comments: {
    id(value: ParamValue<Client["v3"]["comments"][':id']['$delete'], "id">): {
      deleteComment: Client["v3"]["comments"][':id']['$delete'];
    };
  };
  connections: {
    createConnection: Client["v3"]["connections"]['$post'];
    id(value: ParamValue<Client["v3"]["connections"][':id']['$delete'], "id">): {
      deleteConnection: Client["v3"]["connections"][':id']['$delete'];
      getConnection: Client["v3"]["connections"][':id']['$get'];
      moveConnection: Client["v3"]["connections"][':id']["move"]['$post'];
    };
  };
  groups: {
    id(value: ParamValue<Client["v3"]["groups"][':id']['$get'], "id">): {
      getGroup: Client["v3"]["groups"][':id']['$get'];
      getGroupContents: Client["v3"]["groups"][':id']["contents"]['$get'];
      getGroupFollowers: Client["v3"]["groups"][':id']["followers"]['$get'];
    };
  };
  search: {
    search: Client["v3"]["search"]['$get'];
  };
  system: {
    getOpenapiSpec: Client["v3"]["openapi"]['$get'];
    getOpenapiSpecJson: Client["v3"]["openapi.json"]['$get'];
    getPing: Client["v3"]["ping"]['$get'];
  };
  uploads: {
    presignUpload: Client["v3"]["uploads"]["presign"]['$post'];
  };
  users: {
    getCurrentUser: Client["v3"]["me"]['$get'];
    id(value: ParamValue<Client["v3"]["users"][':id']['$get'], "id">): {
      getUser: Client["v3"]["users"][':id']['$get'];
      getUserContents: Client["v3"]["users"][':id']["contents"]['$get'];
      getUserFollowers: Client["v3"]["users"][':id']["followers"]['$get'];
      getUserFollowing: Client["v3"]["users"][':id']["following"]['$get'];
    };
  };
};

function invokeEndpoint(endpoint: Fn, boundParam: Record<string, unknown>, args: unknown[]) {
  if (!boundParam || Object.keys(boundParam).length === 0) return endpoint(...(args as any[]));
  if (args.length > 0 && typeof args[0] === "object" && args[0] !== null) {
    const first = args[0] as Record<string, unknown>;
    const merged = { ...first, param: { ...boundParam, ...(first.param as object | undefined) } };
    return endpoint(merged, ...(args.slice(1) as any[]));
  }
  return endpoint({ param: boundParam }, ...(args as any[]));
}

const OP_HANDLERS: Record<string, (client: Client, bound: Record<string, unknown>, args: unknown[]) => unknown> = {
  "batchCreateBlocks": (client, bound, args) => invokeEndpoint(client.v3.blocks.batch['$post'], bound, args),
  "createBlock": (client, bound, args) => invokeEndpoint(client.v3.blocks['$post'], bound, args),
  "createBlockComment": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id'].comments['$post'], bound, args),
  "createChannel": (client, bound, args) => invokeEndpoint(client.v3.channels['$post'], bound, args),
  "createConnection": (client, bound, args) => invokeEndpoint(client.v3.connections['$post'], bound, args),
  "createOAuthToken": (client, bound, args) => invokeEndpoint(client.v3.oauth.token['$post'], bound, args),
  "deleteChannel": (client, bound, args) => invokeEndpoint(client.v3.channels[':id']['$delete'], bound, args),
  "deleteComment": (client, bound, args) => invokeEndpoint(client.v3.comments[':id']['$delete'], bound, args),
  "deleteConnection": (client, bound, args) => invokeEndpoint(client.v3.connections[':id']['$delete'], bound, args),
  "getBatchStatus": (client, bound, args) => invokeEndpoint(client.v3.blocks.batch[':batch_id']['$get'], bound, args),
  "getBlock": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id']['$get'], bound, args),
  "getBlockComments": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id'].comments['$get'], bound, args),
  "getBlockConnections": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id'].connections['$get'], bound, args),
  "getChannel": (client, bound, args) => invokeEndpoint(client.v3.channels[':id']['$get'], bound, args),
  "getChannelConnections": (client, bound, args) => invokeEndpoint(client.v3.channels[':id'].connections['$get'], bound, args),
  "getChannelContents": (client, bound, args) => invokeEndpoint(client.v3.channels[':id'].contents['$get'], bound, args),
  "getChannelFollowers": (client, bound, args) => invokeEndpoint(client.v3.channels[':id'].followers['$get'], bound, args),
  "getConnection": (client, bound, args) => invokeEndpoint(client.v3.connections[':id']['$get'], bound, args),
  "getCurrentUser": (client, bound, args) => invokeEndpoint(client.v3.me['$get'], bound, args),
  "getGroup": (client, bound, args) => invokeEndpoint(client.v3.groups[':id']['$get'], bound, args),
  "getGroupContents": (client, bound, args) => invokeEndpoint(client.v3.groups[':id'].contents['$get'], bound, args),
  "getGroupFollowers": (client, bound, args) => invokeEndpoint(client.v3.groups[':id'].followers['$get'], bound, args),
  "getOpenapiSpec": (client, bound, args) => invokeEndpoint(client.v3.openapi['$get'], bound, args),
  "getOpenapiSpecJson": (client, bound, args) => invokeEndpoint(client.v3["openapi.json"]['$get'], bound, args),
  "getPing": (client, bound, args) => invokeEndpoint(client.v3.ping['$get'], bound, args),
  "getUser": (client, bound, args) => invokeEndpoint(client.v3.users[':id']['$get'], bound, args),
  "getUserContents": (client, bound, args) => invokeEndpoint(client.v3.users[':id'].contents['$get'], bound, args),
  "getUserFollowers": (client, bound, args) => invokeEndpoint(client.v3.users[':id'].followers['$get'], bound, args),
  "getUserFollowing": (client, bound, args) => invokeEndpoint(client.v3.users[':id'].following['$get'], bound, args),
  "moveConnection": (client, bound, args) => invokeEndpoint(client.v3.connections[':id'].move['$post'], bound, args),
  "presignUpload": (client, bound, args) => invokeEndpoint(client.v3.uploads.presign['$post'], bound, args),
  "search": (client, bound, args) => invokeEndpoint(client.v3.search['$get'], bound, args),
  "updateBlock": (client, bound, args) => invokeEndpoint(client.v3.blocks[':id']['$put'], bound, args),
  "updateChannel": (client, bound, args) => invokeEndpoint(client.v3.channels[':id']['$put'], bound, args),
};

function paramKeysFromGroupSegment(segment: string): string[] {
  if (segment.includes("\x1f")) return segment.split("\x1f").filter(Boolean);
  return segment ? [segment] : [];
}

function normalizeGroupParams(params: string[], value: unknown): Record<string, unknown> {
  if (params.length === 1) return { [params[0]!]: value };
  return value as Record<string, unknown>;
}

type BuilderApplyOpts = { client: Client; path: string[]; args: unknown[]; bound?: Record<string, unknown> };

function builderApply(opts: BuilderApplyOpts): unknown {
  const { client, path, args, bound } = opts;
  if (path.length === 2 && !bound) {
    const seg = path[1]!;
    const op = OP_HANDLERS[seg];
    if (op) return op(client, {}, args);
    const keys = paramKeysFromGroupSegment(seg);
    if (keys.length === 0) return undefined;
    return createBuilderProxy(client, path, normalizeGroupParams(keys, args[0]));
  }
  if (path.length === 3 && bound) {
    const opId = path[2]!;
    const run = OP_HANDLERS[opId];
    return run ? run(client, bound, args) : undefined;
  }
  return undefined;
}

function createBuilderProxy(client: Client, path: string[] = [], bound?: Record<string, unknown>) {
  const proxy: unknown = new Proxy(() => {}, {
    get(_obj, prop) {
      if (typeof prop !== "string" || prop === "then") return undefined;
      return createBuilderProxy(client, [...path, prop], bound);
    },
    apply(_1, _2, args: unknown[]) {
      return builderApply({ client, path, args, bound });
    },
  });
  return proxy;
}

export interface Builder extends BuilderShape {}

export class Builder {
  constructor(client: Client) {
    return createBuilderProxy(client) as unknown as Builder;
  }
}
