/**
 * This file was auto-generated by scripts/generate-operations.ts.
 * DO NOT EDIT BY HAND.
 */

import type { ac } from './client';

type Client = ReturnType<typeof ac>;

export class Operations {
  constructor(protected client: ReturnType<typeof ac>) {}

  batchCreateBlocks(
    ...args: Parameters<Client['v3']['blocks']['batch']['$post']>
  ): ReturnType<Client['v3']['blocks']['batch']['$post']> {
    return this.client.v3.blocks.batch.$post(...args);
  }

  createBlock(
    ...args: Parameters<Client['v3']['blocks']['$post']>
  ): ReturnType<Client['v3']['blocks']['$post']> {
    return this.client.v3.blocks.$post(...args);
  }

  createBlockComment(
    ...args: Parameters<Client['v3']['blocks'][':id']['comments']['$post']>
  ): ReturnType<Client['v3']['blocks'][':id']['comments']['$post']> {
    return this.client.v3.blocks[':id'].comments.$post(...args);
  }

  createChannel(
    ...args: Parameters<Client['v3']['channels']['$post']>
  ): ReturnType<Client['v3']['channels']['$post']> {
    return this.client.v3.channels.$post(...args);
  }

  createConnection(
    ...args: Parameters<Client['v3']['connections']['$post']>
  ): ReturnType<Client['v3']['connections']['$post']> {
    return this.client.v3.connections.$post(...args);
  }

  createOAuthToken(
    ...args: Parameters<Client['v3']['oauth']['token']['$post']>
  ): ReturnType<Client['v3']['oauth']['token']['$post']> {
    return this.client.v3.oauth.token.$post(...args);
  }

  deleteChannel(
    ...args: Parameters<Client['v3']['channels'][':id']['$delete']>
  ): ReturnType<Client['v3']['channels'][':id']['$delete']> {
    return this.client.v3.channels[':id'].$delete(...args);
  }

  deleteComment(
    ...args: Parameters<Client['v3']['comments'][':id']['$delete']>
  ): ReturnType<Client['v3']['comments'][':id']['$delete']> {
    return this.client.v3.comments[':id'].$delete(...args);
  }

  deleteConnection(
    ...args: Parameters<Client['v3']['connections'][':id']['$delete']>
  ): ReturnType<Client['v3']['connections'][':id']['$delete']> {
    return this.client.v3.connections[':id'].$delete(...args);
  }

  getBatchStatus(
    ...args: Parameters<Client['v3']['blocks']['batch'][':batch_id']['$get']>
  ): ReturnType<Client['v3']['blocks']['batch'][':batch_id']['$get']> {
    return this.client.v3.blocks.batch[':batch_id'].$get(...args);
  }

  getBlock(
    ...args: Parameters<Client['v3']['blocks'][':id']['$get']>
  ): ReturnType<Client['v3']['blocks'][':id']['$get']> {
    return this.client.v3.blocks[':id'].$get(...args);
  }

  getBlockComments(
    ...args: Parameters<Client['v3']['blocks'][':id']['comments']['$get']>
  ): ReturnType<Client['v3']['blocks'][':id']['comments']['$get']> {
    return this.client.v3.blocks[':id'].comments.$get(...args);
  }

  getBlockConnections(
    ...args: Parameters<Client['v3']['blocks'][':id']['connections']['$get']>
  ): ReturnType<Client['v3']['blocks'][':id']['connections']['$get']> {
    return this.client.v3.blocks[':id'].connections.$get(...args);
  }

  getChannel(
    ...args: Parameters<Client['v3']['channels'][':id']['$get']>
  ): ReturnType<Client['v3']['channels'][':id']['$get']> {
    return this.client.v3.channels[':id'].$get(...args);
  }

  getChannelConnections(
    ...args: Parameters<Client['v3']['channels'][':id']['connections']['$get']>
  ): ReturnType<Client['v3']['channels'][':id']['connections']['$get']> {
    return this.client.v3.channels[':id'].connections.$get(...args);
  }

  getChannelContents(
    ...args: Parameters<Client['v3']['channels'][':id']['contents']['$get']>
  ): ReturnType<Client['v3']['channels'][':id']['contents']['$get']> {
    return this.client.v3.channels[':id'].contents.$get(...args);
  }

  getChannelFollowers(
    ...args: Parameters<Client['v3']['channels'][':id']['followers']['$get']>
  ): ReturnType<Client['v3']['channels'][':id']['followers']['$get']> {
    return this.client.v3.channels[':id'].followers.$get(...args);
  }

  getConnection(
    ...args: Parameters<Client['v3']['connections'][':id']['$get']>
  ): ReturnType<Client['v3']['connections'][':id']['$get']> {
    return this.client.v3.connections[':id'].$get(...args);
  }

  getCurrentUser(
    ...args: Parameters<Client['v3']['me']['$get']>
  ): ReturnType<Client['v3']['me']['$get']> {
    return this.client.v3.me.$get(...args);
  }

  getGroup(
    ...args: Parameters<Client['v3']['groups'][':id']['$get']>
  ): ReturnType<Client['v3']['groups'][':id']['$get']> {
    return this.client.v3.groups[':id'].$get(...args);
  }

  getGroupContents(
    ...args: Parameters<Client['v3']['groups'][':id']['contents']['$get']>
  ): ReturnType<Client['v3']['groups'][':id']['contents']['$get']> {
    return this.client.v3.groups[':id'].contents.$get(...args);
  }

  getGroupFollowers(
    ...args: Parameters<Client['v3']['groups'][':id']['followers']['$get']>
  ): ReturnType<Client['v3']['groups'][':id']['followers']['$get']> {
    return this.client.v3.groups[':id'].followers.$get(...args);
  }

  getOpenapiSpec(
    ...args: Parameters<Client['v3']['openapi']['$get']>
  ): ReturnType<Client['v3']['openapi']['$get']> {
    return this.client.v3.openapi.$get(...args);
  }

  getOpenapiSpecJson(
    ...args: Parameters<Client['v3']['openapi.json']['$get']>
  ): ReturnType<Client['v3']['openapi.json']['$get']> {
    return this.client.v3['openapi.json'].$get(...args);
  }

  getPing(
    ...args: Parameters<Client['v3']['ping']['$get']>
  ): ReturnType<Client['v3']['ping']['$get']> {
    return this.client.v3.ping.$get(...args);
  }

  getUser(
    ...args: Parameters<Client['v3']['users'][':id']['$get']>
  ): ReturnType<Client['v3']['users'][':id']['$get']> {
    return this.client.v3.users[':id'].$get(...args);
  }

  getUserContents(
    ...args: Parameters<Client['v3']['users'][':id']['contents']['$get']>
  ): ReturnType<Client['v3']['users'][':id']['contents']['$get']> {
    return this.client.v3.users[':id'].contents.$get(...args);
  }

  getUserFollowers(
    ...args: Parameters<Client['v3']['users'][':id']['followers']['$get']>
  ): ReturnType<Client['v3']['users'][':id']['followers']['$get']> {
    return this.client.v3.users[':id'].followers.$get(...args);
  }

  getUserFollowing(
    ...args: Parameters<Client['v3']['users'][':id']['following']['$get']>
  ): ReturnType<Client['v3']['users'][':id']['following']['$get']> {
    return this.client.v3.users[':id'].following.$get(...args);
  }

  moveConnection(
    ...args: Parameters<Client['v3']['connections'][':id']['move']['$post']>
  ): ReturnType<Client['v3']['connections'][':id']['move']['$post']> {
    return this.client.v3.connections[':id'].move.$post(...args);
  }

  presignUpload(
    ...args: Parameters<Client['v3']['uploads']['presign']['$post']>
  ): ReturnType<Client['v3']['uploads']['presign']['$post']> {
    return this.client.v3.uploads.presign.$post(...args);
  }

  search(
    ...args: Parameters<Client['v3']['search']['$get']>
  ): ReturnType<Client['v3']['search']['$get']> {
    return this.client.v3.search.$get(...args);
  }

  updateBlock(
    ...args: Parameters<Client['v3']['blocks'][':id']['$put']>
  ): ReturnType<Client['v3']['blocks'][':id']['$put']> {
    return this.client.v3.blocks[':id'].$put(...args);
  }

  updateChannel(
    ...args: Parameters<Client['v3']['channels'][':id']['$put']>
  ): ReturnType<Client['v3']['channels'][':id']['$put']> {
    return this.client.v3.channels[':id'].$put(...args);
  }
}
